### ISSUE TITLE
Customization of OPUS landing page

### ISSUE THREAD

**Issue by BaptisteCecconi** [mservillat/uws-server#1]
I've installed an instance of OPUS, and I'd like to add some content on the OPUS landing page, to guide the user to the projects and jobs that can be launched from the server. Any guidance for this?

**Comment by mservillat** [comment]
A quick answer is to modify the html template in uws_client/templates/home.html, and add the content inside {% block content %}...{% endblock %}. For a nicer appearance, the html should follow bootstrap3 tags (row, col, panel...), as done in other templates.
We could think of a new feature: include in the home.html a local file (home_local.html?), if it exists.

**Comment by mservillat** [comment]
It is now possible to give a title and content in the settings for the client home page, see last doc : https://github.com/ParisAstronomicalDataCentre/OPUS/blob/master/docs/settings.md
